version: '3.8'

services:
  nginx1:
    image: nginx:alpine
    ports:
      - "8082:83"  # Map port 83 inside the container to port 8080 on the host
    volumes:
      - ./site1:/var/www/html
      - ./site1/nginx.config:/etc/nginx/conf.d/default.conf  # Use the same Nginx configuration for both instances
    depends_on:
      - php1

  nginx2:
    image: nginx:alpine
    ports:
      - "8089:83"  # Map port 83 inside the container to port 8081 on the host
    volumes:
      - ./site2:/var/www/html
      - ./site2/nginx.config:/etc/nginx/conf.d/default.conf  # Use the same Nginx configuration for both instances
    depends_on:
      - php2

  php1:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure you have a Dockerfile at the root of your project
    volumes:
      - ./site1:/var/www/html

  php2:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure you have a Dockerfile at the root of your project
    volumes:
      - ./site2:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
